/**
 * Injects the shared network head (GA4, click events, canonical Person
 * JSON-LD) into every page. The file is generated by
 * alexmercedcom/scripts/build-network-shared.mjs and read at build time, so a
 * regenerate updates the site. Never paste its contents into templates.
 */
const fs = require("fs")
const path = require("path")
const React = require("react")

const headHtml = fs.readFileSync(
  // gatsby-ssr is bundled into .cache, so resolve from the project root.
  path.join(process.cwd(), "network", "network-head.html"),
  "utf-8"
)

const toProps = attrs => {
  const props = {}
  const re = /([a-zA-Z:-]+)(?:="([^"]*)")?/g
  let m
  while ((m = re.exec(attrs))) {
    props[m[1]] = m[2] === undefined ? true : m[2]
  }
  return props
}

const networkHead = []
const scriptRe = /<script([^>]*)>([\s\S]*?)<\/script>/g
let match
let i = 0
while ((match = scriptRe.exec(headHtml))) {
  const props = toProps(match[1])
  const inner = match[2]
  networkHead.push(
    React.createElement("script", {
      key: `network-head-${i++}`,
      ...props,
      ...(inner.trim() ? { dangerouslySetInnerHTML: { __html: inner } } : {}),
    })
  )
}

exports.onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents(networkHead)
}
