[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/og"
  to = "/.netlify/functions/og"
  status = 200